/* counter.svelte.ts generated by Svelte v5.35.2 */
import * as $ from 'svelte/internal/client';

export const counter = (initialCount) => {
	let count = $.tag($.state($.proxy(initialCount)), 'count');
	const getCount = () => $.get(count);

	const increment = () => {
		$.set(count, $.get(count) + 1);
	};

	return { getCount, increment };
};
